# Generated by Django 4.1.6 on 2023-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_subject_question_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('number_of_question', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration of  the quiz in minutes')),
                ('score_to_be_awarded', models.IntegerField(help_text='score to be awarded')),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
