# Generated by Django 4.1.6 on 2023-07-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quiz_remove_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='background',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_logic',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='logic_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_question',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='score_to_be_awarded',
            field=models.IntegerField(default=1, help_text='score to be awarded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=2, help_text='duration of  the quiz in minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
