# Generated by Django 4.1.6 on 2023-07-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_answer_delete_quiz_remove_direction_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('number_of_question', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration of  the quiz in minutes')),
                ('score_to_be_awarded', models.IntegerField(help_text='score to be awarded')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_logic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question_logic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.logic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='logic_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.logic'),
            preserve_default=False,
        ),
    ]
