# Generated by Django 4.1.6 on 2023-07-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_logic_answer_answer_logic_answer_question_logic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_logic',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_logic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='logic_question',
        ),
        migrations.DeleteModel(
            name='Logic',
        ),
    ]
