# Generated by Django 4.1.6 on 2023-07-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_register_delete_user_alter_answer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='register',
        ),
    ]
