# Generated by Django 4.1.6 on 2023-07-20 02:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_register_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='UQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='direction',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_logic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='number_of_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score_to_be_awarded',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time',
        ),
        migrations.AddField(
            model_name='direction',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='is_logic',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='number_of_question',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='score_to_be_awarded',
            field=models.IntegerField(default=1, help_text='score to be awarded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='time',
            field=models.IntegerField(default=1, help_text='duration of  the quiz in minutes'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
