# Generated by Django 4.1.6 on 2023-07-26 12:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_question_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1),
        ),
    ]
