# Generated by Django 4.1.6 on 2023-07-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_direction_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='score_to_be_awarded',
            new_name='score',
        ),
    ]
