# Generated by Django 4.1.6 on 2023-07-27 11:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userresult_incorrect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiona', ckeditor_uploader.fields.RichTextUploadingField()),
                ('questionb', ckeditor_uploader.fields.RichTextUploadingField()),
                ('questionc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('questiond', ckeditor_uploader.fields.RichTextUploadingField()),
                ('correct', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='direction',
            name='content',
        ),
        migrations.AddField(
            model_name='question',
            name='question_photo',
            field=models.ManyToManyField(to='main.content'),
        ),
    ]
