# Generated by Django 4.1.6 on 2023-07-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_content_remove_direction_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_photo',
            field=models.ManyToManyField(blank=True, null=True, to='main.content'),
        ),
    ]
